Fixes error in chrome when you try to inline knockout in your page
Error: Uncaught SyntaxError: Unexpected token ILLEGAL
Reproduce by just pasting knockout into a script tag in a page and
viewing
Caused by "</script>"
Changed to "<" + "/script>"